### PR TITLE
fixed the chapter on undefinable quotients

### PR DESCRIPTION
**Pull request by nicolaikraus**
There are some comments for you in the chapter, but you don't need to clarify something like last time.

### CODE REVIEW

**Comment by nicolaikraus** [comment]
I think the grammar in chapter 7 is fine, I have only added one '\' in the beginning, but then I noticed that it is written well - probably because you have already corrected it for the publication. Ok, so I have finished chapters 4-8, and Ambrus has done 1,2,8 right? So, nearly done...

**Comment by akaposi** [comment]
I have finished chapters 1,2,8. I will look at the abstract and acknowledgements now.

**Comment by akaposi** [comment]
ok, I fixed these too. now I look into chapter 3

**Comment by nicolaikraus** [comment]
I am currently doing chapter 3

**Comment by nicolaikraus** [comment]
Nuo: You should make clear that 'propositional extensionality' is univalence for propositions. Do you define it somewhere?

**Comment by akaposi** [comment]
ok, I also finished parts 3.4-3.6. So now we are done. Nuo, merge the pull requests! :)

**Pull request merged**
