### PR TITLE
definablequotients chapter finished

### PR DESCRIPTION
**Pull request by nicolaikraus**
There are two things which you need to check yourself: 1. in the summary, it says that [-] is the normalisation function, I think it should be the composition of [-] with the projection into the equivalence class; and 2. before Related work, it says something about embedding the natural numbers into the integers, but I think it does not suffice that there is this embedding, the conclusion needs that Z = N + N I think...

### CODE REVIEW

**Comment by nzl-nott** [comment]
1. This is caused by my own ambiguous naming, I sometimes called [-] as the normalisation function, but indeed the normalisation function normalises all objects in one equivalence class to the representative object of it (Is this right?)
2. Maybe you misunderstand my sentences. What I mean here is that: at first Q = Z / N, since we can embed N into Z, Q = Z / Z, so all equations involving Q can be turned into some equations containing only Z, solved by ring solver.

**Comment by nicolaikraus** [comment]
Oh, I see.
1. Yes, you are right, a normalisation function maps all elements of an equivalence class to the same element of this equivalence class. So, a normalisation function usually is an endofunction, i.e. its domain and codomain should be the same type. This is why I thought it's strange if [-] is a normalisation function, because domain and codomain are not the same. [-] : Q0 -> Q. There is a very simple function Q -> Q0, and I think the composition of these two functions (i.e. Q0 -> Q0) is the normalisation function. But I think people will understand what you mean anyway.
1. Ok, I understand. So, maybe I would replace the last sentences before related work by something like this:

When working with the field of rational numbers, we can benefit from the setoid representations. We use Z and N for the definition of Q, and Z itself uses only N. Therefore, any equation of rational numbers amounts to an equation of natural numbers, allowing us to apply the ring solver.

**Comment by nzl-nott** [comment]
1. Do you have a proper name for [-] : Q0 -> Q?
2. That is much better than mine :)

**Comment by nicolaikraus** [comment]
No... not sure what the best name would be, probably 'normalisation function' is ok. I only was confused at first. It is very close to a 'real' normalisation function, and people will understand it.

**Comment by nzl-nott** [comment]
OK, I will leave it as it is then.

**Pull request merged**
